const contractAddress = "0xFF2f2165f17243D54e8d5F77c78607a67F2ccF0E"; // Replace with your own contract address
const chain = 'rinkeby'; // rinkeby, polygon, or ethereum

const welcome_h1 = "Welcome to the Limited Dating Alien Club NFT Collection!!";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = 'The Dating Alien CLub NFT Project is a decentralized, open-source project. Limited collection of 1,111 NFTs consisting of Aliens, men and women trying to blend in to everyday life and are ready to start dating. Lets see who will be the best match.  Phase 1 Project concept Team formation Brainstorming about Aliens Social Media (Instagram/Twitter) all pages through organic growth Phase 2 Creation of 1,111 Dating Aliens NFTs Website version 1 launch Launch Discord Roadmap accouchement Provide giveaways 20 free mints for the community being selected by several criterial Distribution and contest for WL spots Phase 3 Active Marketing social to grow the community Organic community growth Art contests via Discord Pre-mint for those who have get on WL Public sale Phase 1 Phase 4 Listing on Rarity.tools Upcoming Work with influencers for exposure Give away & Airdrops to loyal/dedicated members who hold NFT for 1,111 hours (46.29 days) Phase 5 Coming Soon  ';
const h1_presale_coming_soon = "NFT Drop Coming Soon!!";
const h1_presale_mint = "Pre-Sale Minting Open!!";
const h1_public_mint = "Public Minting Open!!";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale.. 😢";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! 🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 🎉";
const p_public_mint = "No whitelist needed. Public minting is now open! 🎉";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Mint Your Special Alien NFT";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The Dating Alien Club Community";
const button_public_mint = "Mint Your Limited Alien NFT";
const mint_failed = "Minting failed. 😢 Please try again.";
