const contractAddress = "0x7576bEf5771Fb3d5Cf144e3B749230db57912B2E"; // Replace with your own contract address
const chain = 'ethereum'; // rinkeby, polygon, or ethereum

const welcome_h1 = "Welcome to the Limited Dating Alien Club NFT Collection!!";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = 'The Dating Alien Club NFT Project is a decentralized, open-source project that aims to get rid of the stereotype over profile images onlne mainly on Social Media. Our NFT collection of outcast Aleins is the perfect demonstration on how to look at people. By showing NFTs with there interests and not how good looking they are will eventually help with how we look at people. Limited collection of 1,111 NFTs consisting of Aliens, men and women trying to blend in to everyday life and are ready to start dating. Lets see who will be the best match.';
const h1_presale_coming_soon = "NFT Drop Coming Soon!!";
const h1_presale_mint = "Pre-Sale Minting Open!!";
const h1_public_mint = "Public Minting Open!!";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale.. 😢";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! 🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 🎉";
const p_public_mint = "No whitelist needed. Public minting is now open! 🎉";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Mint Your Special Alien NFT";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The Dating Alien Club Community";
const button_public_mint = "Mint Your Limited Alien NFT";
const mint_failed = "Minting failed. 😢 Please try again.";
